# Generated by Django 4.0.5 on 2022-07-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50, unique=True)),
                ('caticon', models.CharField(max_length=100)),
            ],
        ),
    ]
