# Generated by Django 4.0.5 on 2022-07-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='caticon',
            new_name='caticonnm',
        ),
    ]
