# Generated by Django 4.0.5 on 2022-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_rename_caticon_category_caticonnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=50)),
                ('subcatnm', models.CharField(max_length=50, unique=True)),
                ('subcaticonnm', models.CharField(max_length=100)),
            ],
        ),
    ]
