# Generated by Django 4.0.5 on 2022-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('ptitle', models.CharField(max_length=50)),
                ('pcategory', models.CharField(max_length=50)),
                ('psubcategory', models.CharField(max_length=50)),
                ('pdescription', models.CharField(max_length=500)),
                ('pprice', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
