# Generated by Django 4.0.5 on 2022-07-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_payment_info_alter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='info',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
