# Generated by Django 4.0.5 on 2022-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('info', models.CharField(default='test', max_length=50, null=True)),
            ],
        ),
    ]
