# Generated by Django 4.0.5 on 2022-07-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='info',
        ),
    ]
