# Generated by Django 4.0.5 on 2022-07-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='info',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
