# Generated by Django 4.0.5 on 2022-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_payment_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='info',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
